# fly.toml app configuration file generated for skull-king-kt on 2023-09-22T13:11:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skull-king-kt"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  HOST = "skull-king-kt.fly.dev"